backend:
  name: github
  repo: j-rewerts/ore-ero
  branch: netlify
media_folder: "assets/uploads"
collections:
  - name: "administrations"
    label: "Administrations"
    folder: "_data/administrations"
    extension: yml
    identifier_field: "code"
    create: true
    fields:
      - name: "code"
        label: "Code"
        widget: "string"
      - name: "order"
        label: "Order"
        widget: "select"
        options: ["Municipal", "Provincial", "Federal"]
      - name: "parent"
        required: false
        label: "Parent Organization"
        widget: "relation"
        collection: "administrations"
        searchFields: ["name.en", "name.fr"]
        valueField: "code"
        displayFields: ["name.en", "name.fr"]
      - name: "name"
        label: "Name"
        widget: "object"
        fields:
          - name: "en"
            label: "English"
            widget: "string"
          - name: "fr"
            label: "French"
            widget: "string"
  - name: "oss"
    label: "Open Source Software"
    folder: "_data/oss"
    extension: "yml"
    identifier_field: "name_en"
    create: true
    fields:
      - name: "schemaVersion"
        label: "Schema Version"
        widget: "string"
      - name: "description_en"
        label: "English Description"
        widget: "string"
      - name: "description_fr"
        label: "French Description"
        widget: "string"
      - name: "homepageURL_en"
        label: "English Homepage URL"
        widget: "string"
      - name: "homepageURL_fr"
        label: "French Homepage URL"
        widget: "string"
      - name: "licenses"
        label: "Licenses"
        widget: "object"
        fields:
          - name: "URL_en"
            label: "English URL"
            widget: "string"
          - name: "URL_fr"
            label: "French URL"
            widget: "string"
          - name: "spdxID"
            label: "SPDX ID"
            widget: "string"
      - name: "name_en"
        label: "English Name"
        widget: "string"
      - name: "name_fr"
        label: "French Name"
        widget: "string"
      - name: "tags_en"
        label: "English Tags"
        widget: "list"
      - name: "tags_fr"
        label: "French Tags"
        widget: "list"
      - name: "administrations"
        label: "Administrations"
        widget: "object"
        fields:
          - name: "adminCode"
            label: "Admin Code"
            widet: "string"
          - name: uses
            label: "Uses"
            widget: "object"
            fields:
              - name: "contact"
                label: "Contact"
                widget: "object"
                fields:
                  - name: "URL_en"
                    label: "English URL"
                    widget: "string"
                    required: false
                  - name: "URL_fr"
                    label: "French URL"
                    widget: "string"
                    required: false
                  - name: "email"
                    label: "Email"
                    widget: "string"
                  - name: "name"
                    label: "Name"
                    widget: "string"
                    required: false
              - name: "date"
                label: "Date"
                widget: "object"
                fields:
                  - name: "started"
                    label: "Started"
                    widget: "date"
                  - name: "metadataLastUpdated"
                    label: "Metadata Last Updated"
                    widget: "date"
              - name: "description_en"
                label: "English Description"
                widget: "string"
              - name: "description_fr"
                label: "French Description"
                widget: "string"
              - name: "name_en"
                label: "English Name"
                widget: "string"
              - name: "name_fr"
                label: "French NAme"
                widget: "string"
              - name: "relatedCode"
                label: "Related Code"
                widget: "object"
                fields:
                  - name: "URL_en"
                    label: "English URL"
                    widget: "string"
                    required: false
                  - name: "URL_fr"
                    label: "French URL"
                    widget: "string"
                    required: false
                  - name: "name_en"
                    label: "English Name"
                    widget: "string"
                    required: false
                  - name: "name_fr"
                    label: "French Name"
                    widget: "string"
                    required: false
              - name: "status"
                label: "Status"
                widget: "string"
                required: false
              - name: "users"
                label: "Users"
                widget: "string"
                required: false







