backend:
  name: github
  repo: j-rewerts/ore-ero
  branch: netlify
media_folder: "assets/uploads"
collections:
  - name: "administrations"
    label: "Administrations"
    folder: "_data/administrations"
    extension: yml
    summary: "{{name_en}}"
    identifier_field: "code"
    create: true
    fields:
      - name: "code"
        label: "Code"
        widget: "string"
      - name: "order"
        label: "Order"
        widget: "select"
        options: ["Municipal", "Provincial", "Federal"]
      - name: "parent"
        required: false
        label: "Parent Organization"
        widget: "relation"
        collection: "administrations"
        searchFields: ["name_en", "name_fr"]
        valueField: "code"
        displayFields: ["name_en"]
      - name: "name_en"
        label: "English Name"
        widget: "string"
      - name: "name_fr"
        label: "French Name"
        widget: "string"
  - name: "code"
    label: "Code"
    folder: "_data/code"
    extension: "yml"
    summary: "{{name_en}}"
    identifier_field: "name_en"
    create: true
    fields:
      - name: "adminCode"
        label: "Administration Responsible for this Code"
        widget: "relation"
        collection: "administrations"
        searchFields: ["name_en", "name_fr"]
        valueField: "code"
        displayFields: ["name_en"]
      - name: "contactEmail"
        label: "Contact Email"
        widget: "string"
      - name: "contactName"
        label: "Contact Name"
        widget: "string"
        required: false
      - name: "contactPhone"
        label: "Contact Phone Number"
        widget: "string"
        required: false
      - name: "contactURL_en"
        label: "English Contact URL"
        widget: "string"
        required: false
      - name: "contactURL_fr"
        label: "French Contact URL"
        widget: "string"
        required: false
      - name: "created"
        label: "Created Date"
        widget: "date"
        format: "YYYY-MM-DD"
      - name: "lastModified"
        label: "Last Modified"
        widget: "date"
        format: "YYYY-MM-DD"
        required: false
      - name: "metadataLastUpdated"
        label: "Last Time This Form Was Filled Out"
        widget: "date"
        format: "YYYY-MM-DD"
      - name: "description_en"
        label: "English Description"
        widget: "text"
      - name: "description_fr"
        label: "French Description"
        widget: "text"
      - name: "downloadURL_en"
        label: "English Download URL"
        widget: "string"
        required: false
      - name: "downloadURL_fr"
        label: "French Download URL"
        widget: "string"
        required: false
      - name: "homepageURL_en"
        label: "English Homepage URL"
        widget: "string"
        required: false
      - name: "homepageURL_fr"
        label: "French Homepage URL"
        widget: "string"
        required: false
      - name: "languages"
        label: "Languages"
        widget: "list"
      - name: "name_en"
        label: "English Name"
        widget: "string"
      - name: "name_fr"
        label: "French Name"
        widget: "string"
      - name: "partners"
        label: "Partners"
        widget: "list"
        required: false
        fields:
          - name: "partnerCode"
            label: "Partner"
            widget: "relation"
            collection: "administrations"
            searchFields: ["name_en", "name_fr"]
            valueField: "code"
            displayFields: ["name_en"]
      - name: "licenses"
        label: "Licenses"
        widget: "list"
        allow_add: true
        fields: 
          - {name: "url_en", label: "English URL", widget: "string"}
          - {name: "url_fr", label: "French URL", widget: "string"}
          - {name: "spdxID", label: "License Type (MIT, GPL, etc)", widget: "string"}
      - name: "repoURL_en"
        label: "English Repository URL"
        widget: "string"
      - name: "repoURL_fr"
        label: "French Repository URL"
        widget: "string"
      # - name: "relatedCode"
      #   label: "Related Code"
      #   widget: "relation"
      #   collection: "oss"
      #   searchFields: ["name_en", "name_fr"]
      #   valueField: "name_en"
      #   displayFields: ["name_en"]
      #   required: false
      # This might not work for code not referenced in the project (external code)
      - name: "relatedCode"
        label: "Related Code"
        widget: "list"
        fields:
          - name: "relatedCodeURL_en"
            label: "English Related Code URL"
            widget: "string"
            required: false
          - name: "relatedCodeURL_fr"
            label: "French Related Code URL"
            widget: "string"
            required: false
          - name: "relatedCodeName_en"
            label: "English Related Code Name"
            widget: "string"
            required: false
          - name: "relatedCodeName_fr"
            label: "French Related Code Name"
            widget: "string"
            required: false
      - name: "tags_en"
        label: "English Tags"
        widget: "list"
      - name: "tags_fr"
        label: "French Tags"
        widget: "list"
      - name: "vcs"
        label: "Version Control System"
        widget: "string"
        required: false
      - name: "status"
        label: "Status of the project"
        widget: "select"
        options: ["Alpha", "Beta", "Deprecated", "Development", "Maintained", "Production", "Retired"]
        required: false
      - name: "version"
        label: "Version"
        widget: "string"
        required: false
  - name: "oss"
    label: "Open Source Software"
    folder: "_data/logiciels_libres-open_source_software"
    extension: "yml"
    identifier_field: "name_en"
    create: true
    fields:
      - name: "description_en"
        label: "English Description"
        widget: "string"
      - name: "description_fr"
        label: "French Description"
        widget: "string"
      - name: "homepageURL_en"
        label: "English Homepage URL"
        widget: "string"
      - name: "homepageURL_fr"
        label: "French Homepage URL"
        widget: "string"
      - name: "licenses"
        label: "Licenses"
        widget: "list"
        fields:
          - name: "URL_en"
            label: "English URL"
            widget: "string"
          - name: "URL_fr"
            label: "French URL"
            widget: "string"
          - name: "spdxID"
            label: "SPDX ID"
            widget: "string"
      - name: "name_en"
        label: "English Name"
        widget: "string"
      - name: "name_fr"
        label: "French Name"
        widget: "string"
      - name: "tags_en"
        label: "English Tags"
        widget: "list"
      - name: "tags_fr"
        label: "French Tags"
        widget: "list"
      - name: "administrations"
        label: "Administrations"
        widget: "list"
        fields:
          - name: "adminCode"
            label: "Administration Responsible for this Code"
            widget: "relation"
            collection: "administrations"
            searchFields: ["name_en", "name_fr"]
            valueField: "code"
            displayFields: ["name_en"]
          - name: uses
            label: "Uses"
            widget: "list"
            fields:
              - name: "contactURL_en"
                label: "English Contact URL"
                widget: "string"
                required: false
              - name: "contactURL_fr"
                label: "French Contact URL"
                widget: "string"
                required: false
              - name: "contactEmail"
                label: "Contact Email"
                widget: "string"
              - name: "contactName"
                label: "Contact Name"
                widget: "string"
                required: false
              - name: "started"
                label: "Started"
                widget: "date"
              - name: "metadataLastUpdated"
                label: "Metadata Last Updated"
                widget: "date"
              - name: "description_en"
                label: "English Description"
                widget: "string"
              - name: "description_fr"
                label: "French Description"
                widget: "string"
              - name: "name_en"
                label: "English Name"
                widget: "string"
              - name: "name_fr"
                label: "French NAme"
                widget: "string"
              - name: "relatedCodeURL_en"
                label: "English Related Code URL"
                widget: "string"
                required: false
              - name: "relatedCodeURL_fr"
                label: "French Related Code URL"
                widget: "string"
                required: false
              - name: "relatedCodeName_en"
                label: "English Related Code Name"
                widget: "string"
                required: false
              - name: "relatedCodeName_fr"
                label: "French Related Code Name"
                widget: "string"
                required: false
              - name: "status"
                label: "Status"
                widget: "string"
                required: false
              - name: "users"
                label: "Users"
                widget: "list"
                required: false